#!/usr/bin/env python3
import gzip
import re
import urllib.request
import xml.etree.ElementTree as ET
import unicodedata
from pathlib import Path
from difflib import SequenceMatcher

M3U = Path("mi_playlist_final.m3u")
OUT = Path("guide.xml")
MISSING = Path("epg_missing.txt")
MAPPING = Path("epg_mapping.txt")

# Sources generated by the IPTV-org EPG engine are placed in epg-local/.
# Direct EPGShare and IPTV-EPG España remain as fallbacks.
LOCAL_SOURCES = [
    ("IPTV-org Movistar+", Path("epg-local/movistarplus.xml")),
    ("IPTV-org Orange TV", Path("epg-local/orangetv.xml")),
]
REMOTE_SOURCES = [
    ("EPGShare ES1", "https://epgshare01.online/epgshare01/epg_ripper_ES1.xml.gz"),
    ("IPTV-EPG España", "https://iptv-epg.org/files/epg-es.xml"),
]

ALIASES = {
    "movistarclásicoses.es":["M+. Clásicos","M+ Clásicos","Movistar Clásicos"],
    "movistardcine.es":["M+. Cine","M+ Cine","Movistar Cine"],
    "movistardeporteses.es":["Movistar Deportes","M+. Deportes","M+ Deportes"],
    "movistardocumentaleses.es":["M+. Documentales","M+ Documentales","Movistar Documentales"],
    "movistarf1es.es":["M+ F1","M+. F1","Movistar F1"],
    "movistarhitses.es":["M+ Hits","M+. Hits","Movistar Hits"],
    "movistarindiees.es":["M+ Indie","M+. Indie","Movistar Indie"],
    "movistarlaliga.es":["M+ LALIGA","M+. LALIGA","Movistar LALIGA"],
    "movistarlaliga1.es":["M+ LALIGA 1","M+. LALIGA 1","Movistar LALIGA 1"],
    "movistarlaliga2.es":["M+ LALIGA 2","M+. LALIGA 2","Movistar LALIGA 2"],
    "movistarlaliga3.es":["M+ LALIGA 3","M+. LALIGA 3","Movistar LALIGA 3"],
    "movistarlaliga4.es":["M+ LALIGA 4","M+. LALIGA 4","Movistar LALIGA 4"],
    "movistarlaliga5.es":["M+ LALIGA 5","M+. LALIGA 5","Movistar LALIGA 5"],
    "movistarorgulloes.es":["M+ Orgullo","Movistar Orgullo"],
    "movistaroriginaleses.es":["M+ Originales","Movistar Originales"],
    "movistarpluses.es.plus2":["Movistar Plus+ 2","Movistar Plus 2","M+ 2"],
    "movistarvamos2es.es":["M+ Vamos 2","Movistar Vamos 2"],
    "mplusacción.es":["M+ Acción","M+. Acción","Movistar Acción"],
    "mplusclásicoses.es":["M+ Clásicos","M+. Clásicos","Movistar Clásicos"],
    "mpluscomediaes.es":["M+ Comedia","M+. Comedia","Movistar Comedia"],
    "mplusdeporteses.es":["M+ Deportes","M+. Deportes","Movistar Deportes"],
    "mplusestrenos.es":["M+ Estrenos","M+. Estrenos","Movistar Estrenos"],
    "mplusgolf2.es":["M+ Golf 2","M+. Golf 2","Movistar Golf 2"],
    "mplusgolfes.es":["M+ Golf","M+. Golf","Movistar Golf"],
    "mplusligadecampeones2.es":["M+ Liga de Campeones 2","M+. Liga de Campeones 2"],
    "mplusligadecampeones4es.es":["M+ Liga de Campeones 4","M+. Liga de Campeones 4"],
    "mlaliga2.es":["M+ LALIGA 2","M+. LALIGA 2"],
    "mlaliga3.es":["M+ LALIGA 3","M+. LALIGA 3"],
    "mligadecampeones.es":["M+ Liga de Campeones","M+. Liga de Campeones"],
    "mdeportes2.es":["M+ Deportes 2","Movistar Deportes 2"],
    "mdeportes3.es":["M+ Deportes 3","Movistar Deportes 3"],
    "mdramaes.es":["M+ Drama","Movistar Drama"],
    "daznmotogpes.es":["DAZN MotoGP","DAZN Moto GP"],
    "clanes.es":["Clan","Clan TVE","Clan.es"],
    "classicaes.es":["Classica","Classica.es"],
    "cnbces.es":["CNBC Europe","CNBC"],
    "cnninternational.es":["CNN International","CNN Internacional"],
    "cnnintes.es":["CNN International","CNN Internacional"],
    "cocina.es":["Canal Cocina","Cocina"],
    "canaldecasa.es":["Canal Decasa","Decasa"],
    "discoveryes.es":["Discovery Channel","Discovery"],
    "dwenespañoles.es":["Deutsche Welle","DW Español"],
    "elconfidenciales.es":["El Confidencial"],
    "elgaragetves.es":["El Garage TV","El Garage"],
    "elpaíses.es":["El País"],
    "fdf.es":["FDF","Factoría de Ficción"],
    "galiciatv.es":["TV Galicia","TVG","Galicia TV"],
    "tvgaliciaes.es":["TV Galicia","TVG","Galicia TV"],
    "tvgtvgaliciaes.es":["TV Galicia","TVG","Galicia TV"],
    "goltv.es":["GOL TV","GOL"],
    "hittv.es":["Hit TV","HIT TV"],
    "laligahypermotiontv.es":["LALIGA HYPERMOTION TV"],
    "laligahypermotiontv2.es":["LALIGA HYPERMOTION TV 2"],
    "laligahypermotiontv3.es":["LALIGA HYPERMOTION TV 3"],
    "motorvisiontv.es":["Motorvision TV","MotorVision"],
    "natgeowildes.es":["Nat Geo Wild","National Geographic Wild"],
    "navarratves.es":["Navarra TV","Navarra Televisión"],
    "pocoyóes.es":["Pocoyó","Pocoyo"],
    "redbulltv.es":["Red Bull TV","Red Bull"],
    "runtimeacciónes.es":["Runtime Acción"],
    "runtimeclásicoses.es":["Runtime Clásicos"],
    "runtimecomediaes.es":["Runtime Comedia"],
    "runtimecrimenes.es":["Runtime Crimen"],
    "runtimees.es":["Runtime"],
    "runtimeromancees.es":["Runtime Romance"],
    "runtimethrillerplusterrores.es":["Runtime Thriller","Runtime Terror"],
    "sicinternacionales.es":["SIC Internacional"],
    "sinfiltroses.es":["Sin Filtros"],
    "squirreles.es":["Squirrel"],
    "surfchanneles.es":["Surf Channel"],
    "tdp.es":["Teledeporte","TDP"],
    "telemadridintes.es":["Telemadrid Internacional","Telemadrid"],
    "trtworld.es":["TRT World"],
    "tveinternacional.es.plus1":["TVE Internacional"],
    "votv3cast.es":["TV3","TV3 Cataluña","TV3 Cat"],
    "324es.es":["3/24","324"],
    "acontrapluscine.es":["A Contracorriente","A Contracorriente Cine"],
    "amcselektes.es":["AMC Selekt"],
    "amcwestern.es":["AMC Western","AMC Westerns"],
    "aragóntves.es":["Aragón TV"],
    "aragóntvintes.es":["Aragón TV Internacional","Aragón TV Int"],
    "bbcnews.es":["BBC News"],
    "bemadtv.es":["Be Mad","bemad"],
    "canalextremadurasates.es":["Canal Extremadura"],
    "canalparlamentoes.es":["Canal Parlamento"],
    "canalsurandalucíaes.es":["Canal Sur Andalucía","Canal Sur"],
    "cinefeelgoodverditves.es":["Cine Feel Good","Cines Verdi TV"],
    "gh24h1.es":["GH 24H 1","Gran Hermano 24H 1"],
    "gh24h2.es":["GH 24H 2","Gran Hermano 24H 2"],
    "itaavanzadoes.es":["Italiano Avanzado"],
    "itaintermedioes.es":["Italiano Intermedio"],
    "itaprincipiantees.es":["Italiano Principiante"],
    "la8mediterráneoes.es":["La 8 Mediterráneo","La8 Mediterráneo"],
    "maxavances.es":["Max Avances","Max"],
    "mundoserieses.es":["Mundo Series"],
    "tpa7.es":["TPA 7","Asturias 7"],
    "tpa8es.es":["TPA 8","Asturias 8"],
    "tracelatina.es":["Trace Latina","TRACE Latina"],
    "vivircongatoses.es":["Vivir con Gatos"],
    "viznertv.es":["Vizner TV"],
    "vodarktv.es":["Dark","VOD Dark"],
    "voodsea.es":["Odisea","VOD Odisea"],
    "vosyfy.es":["Syfy","VOD Syfy"],
}

def norm(s):
    s = s or ""
    s = unicodedata.normalize("NFKD", s).encode("ascii","ignore").decode().casefold()
    s = s.replace("&amp;","and").replace("&","and")
    s = re.sub(r"[\+\.\-_/|:]+"," ",s)
    s = re.sub(r"\bmovistar\s*plus\b","movistar",s)
    s = re.sub(r"\bm\s*\+\b","mplus",s)
    s = re.sub(r"\bm\s*\.\b","mplus",s)
    s = re.sub(r"[^a-z0-9]+"," ",s)
    return re.sub(r"\s+"," ",s).strip()

def fetch(url):
    req=urllib.request.Request(url,headers={"User-Agent":"Mozilla/5.0"})
    with urllib.request.urlopen(req,timeout=120) as r: data=r.read()
    if data[:2]==b"\x1f\x8b" or url.endswith(".gz"): data=gzip.decompress(data)
    return ET.fromstring(data)

def read_m3u():
    result={}
    for line in M3U.read_text(encoding="utf-8",errors="ignore").splitlines():
        if not line.startswith("#EXTINF"): continue
        m=re.search(r'tvg-id="([^"]+)"',line,re.I)
        if not m: continue
        uid=m.group(1).strip()
        if not uid: continue
        name=line.split(",",1)[1].strip() if "," in line else uid
        result.setdefault(norm(uid),{"id":uid,"name":name})
    return result

def source_names(ch):
    vals=[ch.get("id","")]
    vals += [x.text for x in ch.findall("display-name") if x.text]
    return {norm(x) for x in vals if x}

def target_names(info):
    return {norm(x) for x in [info["id"],info["name"],*ALIASES.get(info["id"],[])] if x}

def match(ch,wanted):
    src=source_names(ch)
    if not src: return None,0,""
    for k,info in wanted.items():
        if src & target_names(info): return k,1.0,"exact/alias"
    best=(None,0)
    for k,info in wanted.items():
        for a in src:
            for b in target_names(info):
                score=SequenceMatcher(None,a,b).ratio()
                if score>best[1]: best=(k,score)
    if best[1]>=0.96: return best[0],best[1],"fuzzy"
    return None,0,""

def load_local():
    roots=[]
    for name,path in LOCAL_SOURCES:
        if not path.exists():
            print(f"Fuente local: {name} -> NO GENERADA")
            continue
        try:
            roots.append((name,ET.parse(path).getroot()))
            print(f"Fuente local: {name} -> OK")
        except Exception as e:
            print(f"Fuente local: {name} -> ERROR {e}")
    return roots

def main():
    wanted=read_m3u()
    print(f"Encontrados {len(wanted)} tvg-id únicos en {M3U.name}")
    mappings={}
    roots=load_local()

    for name,url in REMOTE_SOURCES:
        print(f"\nFuente: {name}")
        try:
            root=fetch(url)
        except Exception as e:
            print(f"  ERROR: {e}")
            continue
        hits=0
        for ch in root.findall("channel"):
            k,score,method=match(ch,wanted)
            if k is None or k in mappings: continue
            mappings[k]={"user_id":wanted[k]["id"],"source_id":ch.get("id",""),
                         "channel":ch,"source":name,"score":score,"method":method}
            hits+=1
        roots.append((name,root))
        print(f"  Coincidencias nuevas: {hits}")

    # Local IPTV-org sources get priority because they were generated directly
    # from the official site's current scraper. Replace only if they match a
    # channel that has not already been claimed by another source.
    local_mappings={}
    for name,root in roots:
        if name not in ("IPTV-org Movistar+","IPTV-org Orange TV"): continue
        hits=0
        for ch in root.findall("channel"):
            k,score,method=match(ch,wanted)
            if k is None or k in mappings or k in local_mappings: continue
            local_mappings[k]={"user_id":wanted[k]["id"],"source_id":ch.get("id",""),
                               "channel":ch,"source":name,"score":score,"method":method}
            hits+=1
        print(f"{name}: coincidencias nuevas: {hits}")
    mappings.update(local_mappings)

    out=ET.Element("tv",{"generator-info-name":"Custom EPG for alvaropah/iptv v7",
                          "generator-info-url":"https://github.com/alvaropah/iptv"})
    for item in sorted(mappings.values(),key=lambda x:x["user_id"].casefold()):
        c=ET.Element("channel",{"id":item["user_id"]})
        for child in item["channel"]: c.append(child)
        out.append(c)

    source_map={(i["source"],i["source_id"]):i["user_id"] for i in mappings.values()}
    seen=set(); programs=0
    for source_name,root in roots:
        for p in root.findall("programme"):
            uid=source_map.get((source_name,p.get("channel","")))
            if not uid: continue
            key=(uid.casefold(),p.get("start",""),p.get("stop",""),"".join(p.itertext())[:500])
            if key in seen: continue
            seen.add(key)
            np=ET.Element("programme",dict(p.attrib)); np.set("channel",uid)
            for child in p: np.append(child)
            out.append(np); programs+=1

    missing=sorted([info["id"] for k,info in wanted.items() if k not in mappings],key=str.casefold)
    MISSING.write_text("\n".join(missing)+("\n" if missing else ""),encoding="utf-8")
    MAPPING.write_text("\n".join(
        f'{i["user_id"]} -> {i["source_id"]} | {i["source"]} | {i["method"]}'
        for i in sorted(mappings.values(),key=lambda x:x["user_id"].casefold())
    )+("\n" if mappings else ""),encoding="utf-8")
    ET.indent(out,space="  "); ET.ElementTree(out).write(OUT,encoding="utf-8",xml_declaration=True)
    print(f"\nEPG generado: {len(mappings)}/{len(wanted)} canales")
    print(f"Programas: {programs}")
    print(f"Sin EPG: {len(missing)}")
    print("Archivos: guide.xml, epg_missing.txt, epg_mapping.txt")

if __name__=="__main__": main()
